import tkinter as tk
win=tk.Tk()
for i in range(5):
    for j in range(3):
        frame=tk.Frame(master=win,relief=tk.RAISED,borderwidth=1)
        frame.grid(row=i,column=j)
        label=tk.Label(master=frame,text=f"Row {i} \n Column {j}")
        label.pack()
win.mainloop()

win=tk.Tk()
for i in range(5):
    for j in range(3):
        frame=tk.Frame(master=win,relief=tk.RAISED,borderwidth=10)
        frame.grid(row=i,column=j,padx=5,pady=5)
        label=tk.Label(master=frame,text=f"Row {i} \n Column {j}")
        label.pack()
win.mainloop()

win=tk.Tk()
username=tk.Label(win,text="Username").place(x=30,y=50)
email=tk.Label(win,text="Email").place(x=30,y=90)
password=tk.Label(win,text="Password").place(x=30,y=130)
login=tk.Button(win,text="Login").place(x=60,y=180)
signup=tk.Button(win,text="SignUp").place(x=120,y=180)
e1=tk.Entry(win).place(x=100,y=50)
e2=tk.Entry(win).place(x=100,y=90)
e3=tk.Entry(win).place(x=100,y=130)

top=tk.Tk()
l1=tk.Label(top, text="Label Demo Text",fg="red",bg="yellow",font="100",justify=tk.LEFT,anchor=tk.NW,width=30,height=1)
b1=tk.Button(top,text="Click Me!",activebackground="purple",activeforeground="white",relief=tk.RAISED,state='normal')
a=tk.IntVar()
def check():
    print(a)
c1=tk.Checkbutton(top, text="Select",variable=a,onvalue=1,offvalue=0,state='normal',indicatoron=True,activebackground="black",activeforeground="white",command=check)
options={"first":1,"Second":2}
for (txt,val) in options.items():
    r1=tk.Radiobutton(top,text=txt,value=val)
e1=tk.Entry(top,show="*")
msg=tk.Message(top,text="Happy Learning:)")
def hello():
    print("Hello")
menubar=tk.Menu(top)
menubar.add_command(label="Hello Students",command=hello)
menubar.add_command(label="Quit",command=top.quit)
top.config(menu=menubar)
mbtn=tk.Menubutton(top,text="courses",relief=tk.RAISED)
mbtn.grid()
mbtn.menu=tk.Menu(mbtn,tearoff=0)
mbtn["menu"]=mbtn.menu
pythonVar=tk.IntVar()
javaVar=tk.IntVar()
phpVar=tk.IntVar()
mbtn.menu.add_checkbutton(label="Python",variable=pythonVar)
mbtn.menu.add_checkbutton(label="Java",variable=javaVar)
mbtn.menu.add_checkbutton(label="PHP",variable=phpVar)
mbtn.pack()
w=tk.Label(top,text="Students",font="90")
w.pack()
frame=tk.Frame(top)
frame.pack()
buttonframe=tk.Frame(top)
buttonframe.pack(side=tk.BOTTOM)
button1=tk.Button(master=frame,text="Block1",fg="red")
button1.pack(side=tk.LEFT)
button2=tk.Button(master=frame,text="Block2",fg="brown")
button2.pack(side=tk.LEFT)
button3=tk.Button(master=frame,text="Block3",fg="blue")
button3.pack(side=tk.LEFT)
button4=tk.Button(master=frame,text="Block4",fg="orange")
button4.pack(side=tk.LEFT)
button5=tk.Button(master=frame,text="Block5",fg="yellow")
button5.pack(side=tk.LEFT)
button6=tk.Button(master=frame,text="Block6",fg="lightgreen")
button6.pack(side=tk.LEFT)
cv=tk.Canvas(top,bg="gray",height="300")
cv.pack()
mCanvas=tk.Canvas(top,bg="white",height=300,width=300)
coord=10,10,300,300
arc1=mCanvas.create_arc(coord,start=0,extent=150,fill="pink")
arc1=mCanvas.create_arc(coord,start=150,extent=215,fill="blue")
mCanvas.pack()
msg.pack()
r1.pack()
e1.pack()
l1.pack()
b1.pack()
c1.pack()
top.mainloop()

